name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete Docker Image and Containers
        run: sudo docker rm -f dweb
      - name: Pull Docker Image from Docker hub
        run : sudo docker pull starlightcandy/songdo:latest
      - name: Execute Docker Container
        run: sudo docker run -d -p 80:3000 --name dweb starlightcandy/songdo:latest
