name: Node CI Workflow

on:
  pull_request:
    branches:
      - main
    push:
      beanches:
        - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run test
